In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('finch.csv', encoding='latin-1')

In [4]:
df

,month,day,year,day_of_year,date,zone,type_of_site,site.number1,number_of_visit,site,...,plumage,beak_length,beak_depth,beak_width,tarsus,wing,mass,pox_IUR,pox_scale,pox_lesion
0,3,18,2022,77,18-Mar-22,Puerto ayora-FCD,Bosque,0.0,0.0,El Barranco,...,0.0,12.06,13.08,10.41,20.03,68.0,21.37,U,NaN,NaN
1,3,18,2022,77,18-Mar-22,Puerto ayora-FCD,Bosque,0.0,0.0,El Barranco,...,4.0,9.21,7.85,7.40,17.00,63.0,13.66,U,NaN,NaN
2,3,18,2022,77,18-Mar-22,Puerto ayora-FCD,Bosque,0.0,0.0,El Barranco,...,5.0,12.77,10.03,8.70,19.80,70.0,21.52,U,NaN,NaN
3,3,18,2022,77,18-Mar-22,Puerto ayora-FCD,Bosque,0.0,0.0,El Barranco,...,4.0,9.02,7.55,7.47,16.93,64.0,9.71,U,NaN,NaN
4,3,18,2022,77,18-Mar-22,Puerto ayora-FCD,Bosque,0.0,0.0,El Barranco,...,0.0,14.10,13.00,11.69,19.10,74.0,26.33,R,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1869,5,18,2023,138,18-May-23,Puerto Ayora,arida,NaN,NaN,Barranco,...,5.0,12.01,10.74,6.09,18.74,NaN,18.24,U,NaN,NaN
1870,5,18,2023,138,18-May-23,Puerto Ayora,arida,NaN,NaN,Barranco,...,5.0,16.04,17.41,8.91,21.15,NaN,32.05,U,NaN,NaN
1871,5,18,2023,138,18-May-23,Puerto Ayora,arida,NaN,NaN,Barranco,...,5.0,15.30,18.23,8.01,21.71,NaN,33.42,R,NaN,NaN
1872,5,18,2023,138,18-May-23,Puerto Ayora,arida,NaN,NaN,Barranco,...,5.0,16.66,17.84,9.57,22.00,NaN,34.42,I,D,NaN
1873,5,18,2023,138,18-May-23,Puerto Ayora,arida,NaN,NaN,Barranco,...,4.0,13.32,15.14,6.94,20.60,NaN,28.17,R,NaN,NaN

In [23]:
prop_dct = {}
site_types = set(df['type_of_site'])
for site in site_types:
    total = 0
    infected = 0
    for row in df.index:
        if df.loc[row, 'type_of_site'] == site:
            total +=1
        if df.loc[row, 'pox_IUR'] == 'I':
            infected += 1
    prop_dct[site] = [infected / total]

In [37]:
infected

127

In [24]:
prop_dct

{'Ganadera': [0.35082872928176795],
 'Bosque': [0.23388581952117865],
 'Agricola': [0.18220946915351507],
 'arida': [0.46691176470588236]}

In [25]:
prop_df = pd.DataFrame(prop_dct)
prop_df

   Ganadera    Bosque  Agricola     arida
0  0.350829  0.233886  0.182209  0.466912

In [44]:
test = df.copy()

In [45]:
dropped_rows = []
for row in test.index:
    if test.loc[row, 'type_of_site'] != 'Agricola':
        dropped_rows.append(row)
test.drop(dropped_rows, inplace=True)

In [46]:
test

,month,day,year,day_of_year,date,zone,type_of_site,site.number1,number_of_visit,site,...,plumage,beak_length,beak_depth,beak_width,tarsus,wing,mass,pox_IUR,pox_scale,pox_lesion
11,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,3.0,8.53,7.30,6.07,17.59,61.0,13.07,U,NaN,NaN
12,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,5.0,8.30,7.58,7.16,17.83,62.0,13.16,R,NaN,NaN
13,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,0.0,8.46,7.15,6.34,16.12,57.0,13.74,U,NaN,NaN
14,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,0.0,8.63,6.89,6.63,16.71,59.0,11.60,R,NaN,NaN
15,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,5.0,9.50,7.63,6.36,15.75,65.0,13.56,U,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,2,23,2023,54,23-Feb-23,Bellavista,Agricola,NaN,NaN,Ma. Elena Guerra,...,0.0,9.34,7.23,5.92,18.01,NaN,13.25,I,B,NaN
1820,4,20,2023,110,20-Apr-23,NaN,Agricola,NaN,NaN,Reina Oleas,...,4.0,9.60,7.80,6.80,19.40,NaN,13.21,R,NaN,NaN
1821,4,20,2023,110,20-Apr-23,NaN,Agricola,NaN,NaN,Reina Oleas,...,0.0,9.40,7.10,5.60,18.20,NaN,12.75,U,NaN,NaN
1822,4,20,2023,110,20-Apr-23,NaN,Agricola,NaN,NaN,Reina Oleas,...,5.0,10.00,7.80,5.30,20.40,NaN,15.56,U,NaN,NaN
1823,4,25,2023,115,25-Apr-23,NaN,Agricola,NaN,NaN,Reina Oleas,...,5.0,14.50,13.90,8.00,21.00,NaN,23.24,I,A,NaN

In [47]:
test2 = test.copy()

In [48]:
dropped_rows = []
for row in test2.index:
    if test2.loc[row, 'pox_IUR'] != 'I':
        dropped_rows.append(row)
test2.drop(dropped_rows, inplace=True)

In [49]:
test2

,month,day,year,day_of_year,date,zone,type_of_site,site.number1,number_of_visit,site,...,plumage,beak_length,beak_depth,beak_width,tarsus,wing,mass,pox_IUR,pox_scale,pox_lesion
16,3,21,2022,80,21-Mar-22,Occidente,Agricola,3.0,1.0,Kelvin Gaona,...,0.0,12.86,12.47,9.96,17.37,67.0,18.74,I,1,1.66
118,4,16,2022,106,16-Apr-22,Occidente,Agricola,5.0,2.0,Kelvin Gaona,...,NaN,9.20,7.47,5.26,16.86,58.0,13.87,I,A,4.22
178,4,28,2022,118,28-Apr-22,Cascajo,Agricola,14.0,2.0,Robert Christen,...,3.0,9.21,7.74,5.22,20.13,65.0,15.34,I,A,3.61
245,5,1,2022,121,1-May-22,Camote,Agricola,17.0,2.0,Clemente Troya,...,NaN,8.76,7.31,4.91,17.86,58.0,13.09,I,A,2.78
254,5,4,2022,124,4-May-22,Cascajo,Agricola,3.0,3.0,Rosa Calva,...,2.0,8.88,7.26,5.33,17.74,61.0,13.09,I,C,7.48
258,5,5,2022,125,5-May-22,Occidente,Agricola,4.0,3.0,Kelvin Gaona,...,NaN,10.95,8.02,5.59,20.16,59.0,14.38,I,C,5.05
261,5,5,2022,125,5-May-22,Occidente,Agricola,4.0,3.0,Kelvin Gaona,...,NaN,9.16,7.07,4.64,18.15,60.0,13.28,I,A,4.05
267,5,5,2022,125,5-May-22,Occidente,Agricola,4.0,3.0,Kelvin Gaona,...,NaN,10.11,7.49,5.26,10.65,59.0,15.00,I,A,5.65
278,5,6,2022,126,6-May-22,Santa Rosa,Agricola,5.0,3.0,Carmen Ramon,...,NaN,10.29,7.94,5.66,18.37,59.0,13.69,I,B,3.53
279,5,6,2022,126,6-May-22,Santa Rosa,Agricola,5.0,3.0,Carmen Ramon,...,3.0,9.86,7.53,5.16,18.43,62.0,14.94,I,A,3.27
413,5,24,2022,144,24-May-22,Santa Rosa,Agricola,15.0,3.0,Ana Chapi,...,5.0,9.98,7.02,5.94,16.23,61.0,14.37,I,A,3.42
424,5,25,2022,145,25-May-22,Cascajo,Agricola,16.0,3.0,Robert Christen,...,NaN,8.46,7.19,5.42,16.21,59.0,14.26,I,A,4.33
451,5,31,2022,151,31-May-22,Occidente,Agricola,1.0,4.0,Kelvin Gaona,...,NaN,10.05,7.25,5.56,18.08,59.0,13.75,I,A,3.69
458,5,31,2022,151,31-May-22,Occidente,Agricola,1.0,4.0,Kelvin Gaona,...,NaN,10.82,6.95,5.21,18.64,62.0,12.34,I,C,4.24
472,6,4,2022,155,4-Jun-22,Cascajo,Agricola,2.0,4.0,Rosa Calva,...,NaN,8.90,6.90,6.00,17.70,59.0,13.67,I,A,2.00
489,6,4,2022,155,4-Jun-22,Cascajo,Agricola,2.0,4.0,Rosa Calva,...,4.0,9.01,7.58,5.17,18.29,64.0,15.26,I,A,2.21
496,6,6,2022,157,6-Jun-22,Santa Rosa,Agricola,3.0,4.0,Carmen Ramon,...,5.0,10.00,7.86,6.11,16.81,62.0,14.03,I,A,2.66
499,6,6,2022,157,6-Jun-22,Santa Rosa,Agricola,3.0,4.0,Carmen Ramon,...,NaN,10.12,7.66,5.89,15.87,58.0,12.78,I,A,2.06
500,6,6,2022,157,6-Jun-22,Santa Rosa,Agricola,3.0,4.0,Carmen Ramon,...,NaN,9.62,6.95,5.45,17.91,59.0,13.29,I,C,5.56
501,6,6,2022,157,6-Jun-22,Santa Rosa,Agricola,3.0,4.0,Carmen Ramon,...,NaN,10.72,7.44,5.55,15.91,62.0,13.00,I,A,1.31
506,6,6,2022,157,6-Jun-22,Santa Rosa,Agricola,3.0,4.0,Carmen Ramon,...,NaN,9.84,7.26,5.84,15.55,59.0,13.46,I,A,1.62
596,7,5,2022,186,5-Jul-22,Cascajo,Agricola,14.0,4.0,Robert Christen,...,NaN,10.04,7.38,5.88,17.46,60.0,13.37,I,B,3.38
648,7,12,2022,193,12-Jul-22,Cascajo,Agricola,2.0,5.0,Rosa Calva,...,4.0,11.20,8.80,6.60,18.40,64.0,16.59,I,B,2.30
654,7,12,2022,193,12-Jul-22,Cascajo,Agricola,2.0,5.0,Rosa Calva,...,NaN,10.10,6.80,5.90,17.20,68.0,13.40,I,A,1.80
661,7,12,2022,193,12-Jul-22,Cascajo,Agricola,2.0,5.0,Rosa Calva,...,NaN,9.05,7.90,5.40,17.00,61.0,13.24,I,A,3.30
664,7,12,2022,193,12-Jul-22,Cascajo,Agricola,2.0,5.0,Rosa Calva,...,NaN,10.30,6.70,5.50,16.50,59.0,13.22,I,B,2.50
667,7,12,2022,193,12-Jul-22,Cascajo,Agricola,2.0,5.0,Rosa Calva,...,5.0,8.70,7.80,5.15,18.00,61.0,13.07,I,A,2.80
681,7,13,2022,194,13-Jul-22,Santa Rosa,Agricola,3.0,5.0,Carmen Ramon,...,NaN,10.50,7.40,5.70,16.00,59.0,12.87,I,B,2.20
690,7,13,2022,194,13-Jul-22,Santa Rosa,Agricola,3.0,5.0,Carmen Ramon,...,NaN,9.60,7.50,6.20,17.00,68.0,12.35,I,A,3.40
726,8,4,2022,216,4-Aug-22,Camote,Agricola,9.0,5.0,Clemente Troya,...,5.0,9.25,7.71,4.81,17.28,64.0,15.21,I,A,3.46
792,8,16,2022,228,16-Aug-22,Santa Rosa,Agricola,11.0,5.0,Ana Chapi,...,5.0,8.95,7.74,5.48,18.87,64.0,14.89,I,A,3.37
965,8,30,2022,242,30-Aug-22,Occidente,Agricola,2.0,6.0,Mario Piu,...,5.0,10.17,8.29,5.40,19.17,61.0,14.05,I,B,3.67
1013,8,31,2022,243,31-Aug-22,Cascajo,Agricola,3.0,6.0,Rosa Calva,...,5.0,12.97,12.51,7.75,19.26,70.0,NaN,I,B,6.94
1020,9,1,2022,244,1-Sep-22,Santa Rosa,Agricola,4.0,6.0,Carmen Ramon,...,5.0,13.45,12.81,8.82,20.05,71.0,21.51,I,A,2.98
1021,9,1,2022,244,1-Sep-22,Santa Rosa,Agricola,4.0,6.0,Carmen Ramon,...,5.0,10.22,7.50,5.86,18.88,64.0,14.35,I,A,2.50
1022,9,1,2022,244,1-Sep-22,Santa Rosa,Agricola,4.0,6.0,Carmen Ramon,...,5.0,13.53,11.97,8.04,20.30,69.0,21.57,I,B,3.87
1124,9,12,2022,255,12-Sep-22,Santa Rosa,Agricola,9.0,6.0,Ana Chapi,...,5.0,9.13,7.75,4.92,18.10,66.0,14.91,I,A,4.21
1344,9,28,2022,271,28-Sep-22,Santa Rosa,Agricola,1.0,7.0,Carmen Ramon,...,NaN,13.50,11.22,7.62,20.52,68.0,21.26,I,C,5.44
1429,10,3,2022,276,3-Oct-22,Cascajo,Agricola,4.0,7.0,Rosa Calva,...,5.0,9.00,6.76,5.84,19.27,63.0,12.20,I,C,3.59
1737,2,23,2023,54,23-Feb-23,Bellavista,Agricola,NaN,NaN,Ma. Elena Guerra,...,0.0,10.24,7.32,5.06,19.15,NaN,13.85,I,A,NaN
1741,2,23,2023,54,23-Feb-23,Bellavista,Agricola,NaN,NaN,Ma. Elena Guerra,...,0.0,10.04,7.76,5.35,19.55,NaN,15.34,I,A,NaN
1743,2,23,2023,54,23-Feb-23,Bellavista,Agricola,NaN,NaN,Ma. Elena Guerra,...,3.0,10.66,7.69,5.87,19.25,NaN,15.74,I,B,NaN
1744,2,23,2023,54,23-Feb-23,Bellavista,Agricola,NaN,NaN,Ma. Elena Guerra,...,0.0,9.34,7.23,5.92,18.01,NaN,13.25,I,B,NaN
1823,4,25,2023,115,25-Apr-23,NaN,Agricola,NaN,NaN,Reina Oleas,...,5.0,14.50,13.90,8.00,21.00,NaN,23.24,I,A,NaN

In [50]:
44/697

0.06312769010043041